### ISSUE TITLE
Theme moves upwards when list is too long

### ISSUE THREAD

**Issue by Nova1ite** [warrayquipsome/Chillax#23]
Theme moves upwards whenever I use pin lists that are too long

![Screenshot 2023-12-12 150705](https://github.com/warrayquipsome/Chillax/assets/115776661/2bc5b6ce-93bb-44ab-b791-cfe24df4e78c)

**Comment by Nova1ite** [comment]
Wanted to add that using ChannelTabs makes it move up this much, if it's disabled, it's less noticeable, but still there.

**Comment by Inmoresentum** [comment]
A temp fix for the current issue is to add the below css by @LofiTurtle. The issue will be fixed in the upcoming **release**.

```css
/* remove date divider */
.hasContent__8519e {
  display: none;
}

/* Un-hide unread divider with date */
.isUnread__6f880 {
  display: flex !important;
}

/* Hide date in unread divider */
.content_d67847 {
  display: none;
}
```
