### ISSUE TITLE
broken small mute panel

### ISSUE THREAD

**Issue by hi-reeve** [warrayquipsome/Chillax#36]
the latest discord update on mac broke the mute panel.

<img width="310" alt="image" src="https://github.com/warrayquipsome/Chillax/assets/45350572/5bd31143-5277-4833-9517-d7386364ce3f">

**Comment by Inmoresentum** [comment]
Actually, this is a known issue with the [Vencord Game Activity Toggle Plugin](https://vencord.dev/plugins/GameActivityToggle). If you plan on using this plugin, please use the below css snippet (*Paste it at very bottom*). 

Note: If you don't know already you can press `ctrl` + `,` (*press and hold `ctrl` and `,` at the same time*) which will take you to the settings menu.

```css
.avatarWrapper__500a6 {
    min-width: 36px !important;
}
.avatarWrapper__500a6:hover {
    min-width: 207px !important;
}
.panels__58331 > .container_debb33 .flex_f18b02 > :not(:last-child) {
    width: 38px !important;
}
.theme-dark .panels__58331 > .container_debb33:hover .flex_f18b02 > :not(:last-child) {
    margin-left: 0px !important;
}
```

And if you don't plan on using the plugin, then you can just disable the plugin from the settings menu vencord tab.

I hope this helps. If you have more questions or issues you can continue the conversation here or alternatively join our [support discord server](https://discord.com/invite/DrfX6286kF) and ask questions there as well. If this solves the issue, please close it at your earliest convenience. Thanks :)
