### ISSUE TITLE
Light theme user sidebar

### ISSUE THREAD

**Issue by donCESAR12345** [warrayquipsome/Chillax#42]
When using the theme with Vesktop in light mode the sidebar for users in servers appears dark when hovering over it.
Without hovering, colors are fine.
![image](https://github.com/warrayquipsome/Chillax/assets/64916276/37548d5f-9e31-45c4-936b-5d64ef12c1d6)
When hovering it becomes dark.
![image](https://github.com/warrayquipsome/Chillax/assets/64916276/933276e9-93c5-4691-8685-8541d9b4047f)
This really breaks the aesthetic, so I would expect this to be a bug.

**Comment by Inmoresentum** [comment]
Hi! You can use the below css snippet to easilly change the color of the `memberlist` when you hover over it.

```css
/* Changes the hover color on avatar only member only list */
.members__573eb:hover {
    background-color: #CECBF0; /*change it if you need to*/
}
```

In the next release we will match it with the color scheme. For more css snippets please join our discord server if you have not already.
