### ISSUE TITLE
Cant scroll down server list

### ISSUE THREAD

**Issue by Fruit911** [warrayquipsome/Chillax#64]
Hi, downloaded the theme and tryed it. it looks fire. but when using it i cant scroll down my servers/folders so i have to disable it everytime i need to scroll down. any fix?

**Comment by Inmoresentum** [comment]
Yes, we are aware of the issue and there is a temporary fix (_credits @LofiTurtle_) for the time being. Please find the css snippet attached below to this message which should fix the issue.

```css
.scroller_ef3116 {
  display: block !important;
  overflow: hidden scroll !important;
}
```


-- [Inmoresentum](https://github.com/Inmoresentum)
